---
name: connectioninfo

containers:
  - dockerfile: Dockerfile
    context: .
    rebuild:
      root: /srv
     command: ./gradlew test fatJar
      sources:
        - build.gradle
        - settings.gradle
        - gradle.properties
        - gradlew
        - src

profiles:
  dev:
    name: development
    namespace: development
    replicas: 3
  stable:
    name: stable
    namespace: stable

branches:
  master: dev
  dev/*:  dev