---
apiVersion: v1
kind: Service
metadata:
  name: connectioninfo
  namespace: {{ build.profile.namespace }}
spec:
  selector:
    app: connectioninfo
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      targetPort: http-api