---
name: echo

containers:
  - dockerfile: Dockerfile
    context: .
    rebuild:
      root: /srv
      command: ./gradlew test fatJar
      sources:
        - build.gradle
        - settings.gradle
        - gradle.properties
        - gradlew
        - src

profiles:
  dev:
    name: development
    namespace: development
    replicas: 1
  stable:
    name: stable
    namespace: stable
    replicas: 3

branches:
  master: stable
  dev/*:  dev
