---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: echo
  namespace: {{ build.profile.namespace }}
  labels:
    app: echo
spec:
  replicas: {{ build.profile.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: {{ build.images["Dockerfile"] }}
          ports:
            - name: http-api
              containerPort: 4567