---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: {{ build.profile.namespace }}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: echo-{{ build.profile.namespace }}
      prefix: /
      host: echo-{{ build.profile.namespace }}.datawire.io
      service: echo.{{ build.profile.namespace }}
spec:
  selector:
    app: echo
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      targetPort: http-api